### ISSUE TITLE
WebConsole does not start

### ISSUE THREAD

**Issue by davidpodhola** [spalarus/docker-karaf#1]
Hi, thanks for a great Docker Karaf container. Unfortunately I am unable to get the WebConsole working.
I followed the sample provided, but there seems to be a problem. Please see the screenshot attached.
Thanks a lot! David
![screenshot from 2018-07-10 09-26-57](https://user-images.githubusercontent.com/436605/42495531-9f48a824-8423-11e8-9f13-14b864b49710.png)

**Comment by spalarus** [comment]
Hi, please try to publish ports to host in explicit way ( -p 8181:8181).

```shell
docker run --rm -it -e KARAF_INIT_COMMANDS="feature:install scr; feature:install webconsole;"  -p 8181:8181 spalarus/karaf
karaf: Ignoring predefined value for KARAF_HOME
        __ __                  ____      
       / //_/____ __________ _/ __/      
      / ,<  / __ `/ ___/ __ `/ /_        
     / /| |/ /_/ / /  / /_/ / __/        
    /_/ |_|\__,_/_/   \__,_/_/         

  Apache Karaf (4.1.7)

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown Karaf.

karaf@root()> feature:list | grep webconsole
webconsole                    │ 4.1.7            │ x        │ Started     │ standard-4.1.7                    │ Base support of the Karaf WebConsole
```

You can check the installed feature by karaf-command _feature:list_.

Cheers
Sebastian

**Comment by davidpodhola** [comment]
Thanks, as far as I remember that worked at the end.
